import Image from 'next/image';
import {Header} from '@/components/Header';
import {ContactLink} from '@/components/ContactLink';
import {SectionHeading} from '@/components/SectionHeading';
import {LeadForm} from '@/components/LeadForm';
import {Map} from '@/components/Map';
import {site,services,reviews,publicUrl} from '@/lib/site';
export default function Home(){
 const schema={'@context':'https://schema.org','@type':'Dentist',name:site.name,telephone:'+'+site.phone,...(publicUrl?{url:publicUrl,image:publicUrl+'/images/melissa-hero.jpg'}:{}),address:{'@type':'PostalAddress',streetAddress:site.street,addressLocality:site.city,addressRegion:site.region,postalCode:site.postalCode,addressCountry:'BR'},geo:{'@type':'GeoCoordinates',latitude:-16.4661296,longitude:-54.6321389},hasMap:site.maps,sameAs:[site.instagram],openingHoursSpecification:[{'@type':'OpeningHoursSpecification',dayOfWeek:['Monday','Tuesday','Wednesday','Thursday','Friday'],opens:'08:00',closes:'18:00'},{'@type':'OpeningHoursSpecification',dayOfWeek:'Saturday',opens:'08:00',closes:'11:00'}]};
 return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/><a className="skip-link" href="#conteudo">Pular para o conteúdo</a><Header/><main id="conteudo"><section id="inicio" className="hero"><div className="shell hero-grid"><div className="hero-copy"><p className="eyebrow"><span className="little-line"/> ODONTOLOGIA EM RONDONÓPOLIS · MT</p><h1>Seu sorriso merece <em>cuidado.</em><br/>Você merece atenção.</h1><p className="hero-description">Odontologia e tratamento de canal em Rondonópolis com a Dra. Melissa Randazzo. Dê o primeiro passo: converse pelo WhatsApp e consulte os horários disponíveis.</p><ContactLink placement="hero"/><p className="hero-note">Um novo cuidado começa com uma conversa.</p><a className="hero-google" href="#avaliacoes"><span className="stars" aria-label="5 de 5 estrelas">★★★★★</span><span><strong>5,0 no Google</strong> <span className="muted">· 3 avaliações</span></span></a></div><div className="hero-visual"><div className="photo-frame"><Image src="/images/melissa-hero.jpg" alt="Dra. Melissa Randazzo em seu consultório" width={434} height={504} priority sizes="(max-width: 760px) 90vw, 43vw"/><div className="photo-caption"><span>Dra. Melissa Randazzo</span><small>CIRURGIÃ-DENTISTA · {site.cro}</small></div></div><span className="vertical-note" aria-hidden="true">CUIDADO QUE COMEÇA EM VOCÊ</span></div></div></section><div className="trust-band"><div className="shell trust-grid"><div><span className="trust-number">01</span><p>Especialização<br/><strong>em Endodontia</strong></p></div><div><span className="trust-number">02</span><p>Atendimento no<br/><strong>Centro de Rondonópolis</strong></p></div><div><span className="trust-number">03</span><p>Agendamento<br/><strong>direto pelo WhatsApp</strong></p></div></div></div>
 <section id="servicos" className="section shell"><div className="section-top"><SectionHeading eyebrow="CUIDADOS PARA O SEU SORRISO" title="Cada sorriso, um ponto de partida." text="Conheça os atendimentos e converse sobre o que você precisa."/><a className="text-link" href="#contato">Encontre seu próximo passo ↗</a></div><div className="services-layout"><div className="service-photo"><Image src="/images/atendimento.jpg" alt="Dra. Melissa realizando atendimento odontológico com equipamentos de proteção" width={547} height={495} sizes="(max-width:760px) 90vw, 40vw"/><span>ATENÇÃO A CADA DETALHE</span></div><div className="service-list">{services.map((s,i)=><article key={s.name}><div className="service-meta"><span>0{i+1}</span><span>{s.category}</span></div><h3>{s.name}</h3><p>{s.text}</p><ContactLink placement={'service_'+i} className="text-link" message={`Olá, Dra. Melissa! Encontrei o site e gostaria de saber sobre ${s.name.toLowerCase()}.`}>Conversar sobre este cuidado</ContactLink></article>)}</div></div></section>
 <section className="difference section"><div className="shell"><SectionHeading eyebrow="MAIS PERTO DE VOCÊ" title="Confiança nos detalhes."/><div className="difference-grid">{[['Formação em Endodontia','A especialização da Dra. Melissa direciona o cuidado voltado ao tratamento de canal.'],['Uma localização acessível','Consultório no Centro, com entrada acessível para pessoas em cadeira de rodas, conforme o perfil no Google.'],['Contato sem complicação','Consulte horários e tire dúvidas sobre o agendamento diretamente pelo WhatsApp.']].map(([title,text],i)=><article key={title}><span className="line-icon" aria-hidden="true">{['◈','⌖','↗'][i]}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
 <section id="sobre" className="section shell about-grid"><div className="about-photo"><Image src="/images/melissa-sobre.jpg" width={410} height={549} alt="Retrato profissional da Dra. Melissa Randazzo" sizes="(max-width:760px) 90vw, 35vw"/></div><div className="about-copy"><SectionHeading eyebrow="CONHEÇA SUA DENTISTA" title="Dra. Melissa Randazzo"/><p className="about-lead">Cuidar do sorriso começa por olhar para a pessoa.</p><p>Cirurgiã-dentista em Rondonópolis, Melissa Randazzo é graduada em Odontologia e especialista em Endodontia. Seu consultório fica no Centro da cidade, com contato direto para você iniciar seu atendimento.</p><p>Da primeira conversa à avaliação, o próximo passo é entender o que seu sorriso precisa.</p><div className="credentials"><span>{site.cro}</span><span>Especialização em Endodontia</span></div><ContactLink href={site.instagram} event="instagram_click" placement="about" className="text-link">Conheça também no Instagram</ContactLink></div></section>
 <section id="avaliacoes" className="reviews-section section"><div className="shell"><div className="section-top"><SectionHeading eyebrow="EXPERIÊNCIAS REAIS" title="A confiança de quem já veio."/><div className="rating"><strong>5,0</strong><div><span className="stars" aria-label="5 de 5 estrelas">★★★★★</span><p>3 avaliações no Google</p></div></div></div><div className="reviews-grid">{reviews.map(r=><figure key={r.name}><span className="stars" aria-label="5 de 5 estrelas">★★★★★</span><blockquote>“{r.text}”</blockquote><figcaption><span className="avatar" aria-hidden="true">{r.name.charAt(0).toUpperCase()}</span><div><strong>{r.name}</strong><small>Avaliação no Google</small></div></figcaption></figure>)}</div><div className="reviews-bottom"><p>Depoimentos transcritos do Google. Consulta em {site.verifiedAt}.</p><ContactLink href={site.maps} event="map_click" placement="reviews" className="text-link">Ver avaliações no Google</ContactLink></div></div></section>
 <section className="section shell"><SectionHeading eyebrow="É SIMPLES COMEÇAR" title="Seu próximo cuidado, em três passos."/><div className="steps">{[['Vamos conversar','Clique no WhatsApp ou preencha o formulário com seu interesse.'],['Encontre um horário','Consulte a disponibilidade e confirme seu agendamento com a clínica.'],['Venha para sua avaliação','Converse com a Dra. Melissa e entenda os próximos passos do seu cuidado.']].map(([title,text],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
 <section id="localizacao" className="location-section"><div className="shell location-grid"><div><SectionHeading eyebrow="ESPERAMOS POR VOCÊ" title="Seu cuidado tem endereço."/><address>{site.street}<br/>{site.district} · {site.city} – {site.region}<br/>CEP {site.postalCode}</address><dl className="hours"><div><dt>Segunda a sexta</dt><dd>08h às 18h</dd></div><div><dt>Sábado</dt><dd>08h às 11h</dd></div><div><dt>Domingo</dt><dd>Fechado</dd></div></dl><p className="muted small">Consulte a disponibilidade e os horários em feriados.</p><ContactLink href={site.maps} event="map_click" placement="location" className="button button-outline">Como chegar</ContactLink></div><Map/></div></section>
 <section id="contato" className="section shell contact-grid"><div><SectionHeading eyebrow="VAMOS CONVERSAR" title="Reserve um momento para você." text="Preencha seus dados para preparar sua mensagem ou fale diretamente pelo WhatsApp."/><ContactLink placement="contact" className="text-link">Prefiro conversar pelo WhatsApp</ContactLink><div className="contact-detail"><p>Também pode ligar</p><ContactLink href={'tel:+'+site.phone} event="phone_click" placement="contact_phone" className="phone-link">{site.phoneLabel}</ContactLink></div><Image className="contact-photo" src="/images/melissa-consultorio.jpg" alt="Dra. Melissa no ambiente do consultório" width={433} height={537} sizes="(max-width:760px) 90vw, 30vw"/></div><LeadForm/></section>
 <section className="final-cta"><div className="shell"><p className="eyebrow">DRA. MELISSA RANDAZZO · RONDONÓPOLIS</p><h2>O primeiro passo para cuidar<br/>do seu sorriso é <em>seu.</em></h2><ContactLink placement="final" className="button button-light">Agendar minha avaliação</ContactLink><p>Fale pelo WhatsApp e consulte os horários disponíveis.</p></div></section></main><footer className="footer shell"><div><a className="brand" href="#inicio">Melissa Randazzo<span>ODONTOLOGIA · {site.cro}</span></a><p>{site.street} · Centro<br/>Rondonópolis – MT</p></div><div className="footer-links"><ContactLink href={site.instagram} event="instagram_click" placement="footer" className="text-link">Instagram</ContactLink><ContactLink placement="footer" className="text-link">WhatsApp</ContactLink><a href="/privacidade">Política de privacidade</a></div><small>© {new Date().getFullYear()} Dra. Melissa Randazzo. Todos os direitos reservados.</small></footer><ContactLink placement="floating" className="floating-whatsapp"><svg viewBox="0 0 24 24" width="25" height="25" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><path d="M20.5 11.5a8.5 8.5 0 0 1-12.7 7.4L3 20l1.2-4.7a8.5 8.5 0 1 1 16.3-3.8Z"/><path d="M8 7c-2 3 3 8 6 8l2-2-3-1-1 1-2-2 1-1-1-3Z"/></svg><span className="floating-label">Agendar</span></ContactLink></>;
}
